-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Nov 22, 2016 at 11:47 PM
-- Server version: 5.5.52-cll-lve
-- PHP Version: 5.4.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `wustagpl_hackohio16`
--

-- --------------------------------------------------------

--
-- Table structure for table `bigtags`
--

CREATE TABLE IF NOT EXISTS `bigtags` (
  `bigtag_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tag_id` int(10) unsigned DEFAULT NULL,
  `parent_tag_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`bigtag_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=14 ;

--
-- Dumping data for table `bigtags`
--

INSERT INTO `bigtags` (`bigtag_id`, `tag_id`, `parent_tag_id`) VALUES
(1, 1, 0),
(2, 11, 0),
(3, 13, 0),
(4, 2, 1),
(5, 3, 1),
(6, 7, 1),
(7, 8, 1),
(8, 9, 1),
(9, 10, 1),
(10, 12, 2),
(11, 14, 3),
(12, 15, 3),
(13, 16, 3);

-- --------------------------------------------------------

--
-- Table structure for table `codes`
--

CREATE TABLE IF NOT EXISTS `codes` (
  `code_id` int(11) NOT NULL,
  `field` int(11) DEFAULT NULL,
  `lookup` varchar(45) DEFAULT NULL,
  `tag_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`code_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

CREATE TABLE IF NOT EXISTS `events` (
  `event_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` tinytext,
  `location` tinytext,
  `desc` text,
  `source1` tinytext,
  `source2` tinytext,
  `time_start` tinytext,
  `time_end` tinytext,
  `importance` int(11) DEFAULT '2',
  `approved` int(11) DEFAULT '0',
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `event_id_UNIQUE` (`event_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=294 ;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`event_id`, `name`, `location`, `desc`, `source1`, `source2`, `time_start`, `time_end`, `importance`, `approved`) VALUES
(284, 'Triangle Fraternity Educational Outreach Scholarship', '', 'Scholarships will be awarded based on character and merit for <strong>first-year male STEM majors</strong>. Judgment will be based off of the individual’s application, first college semester GPA, and personal interviews. Award amounts will be between 200 and 1,000 dollars and will be awarded to the top outstanding gentlemen, up to 10 may be chosen. An applicant must be in his first year at Ohio State and majoring in an engineering, science, math, or architecture field. If an interested applicant’s major is engineering undecided, or they are changing into an eligible major, they are eligible and encouraged to apply. Undecided or exploration majors are judged eligible on an individual basis. Fraternal involvement with Triangle fraternity will not be a factor in judgments.<br><strong>Preliminary application must be submitted by December 1st for full consideration.</strong> Send physical applications to 45 E Lane Columbus, OH or email to <a href="mailto:Jacobs.272@osu.edu" target="_blank" rel="noreferrer noopener external">Jacobs.272@osu.edu</a> . Scholarship interviews will be scheduled after the initial application is received. GPA from applicants first semester at OSU will be used as a factor in award judgment. Scholarships will be awarded in January. <strong><a href="https://docs.google.com/forms/d/e/1FAIpQLSdlm_ccTxWGOi4om6mBXP6xm406XOPxNX_aEwyoNy8MCku2_w/formResponse" target="_blank" rel="noreferrer noopener external">Fill out the online form here to apply.</a></strong>', 'teamup', '2193528', '2016-11-21T00:00:00', '2016-11-21T23:59:00', 2, 0),
(282, 'Football @ Michigan State', '', 'null', 'teamup', '836635', '2016-11-19T12:00:00', '2016-11-19T15:00:00', 2, 0),
(283, 'Summer Program in Biostatistics & Computational Biology at the Harvard T.H. Chan School of Public Health', 'Harvard T.H. Chan School of Public Health', 'The Summer Program is an intensive 6-week program, during which qualified participants (from underrepresented groups in graduate education) receive a whirlwind introduction to biostatistics, epidemiology, and public health research. This program is designed to expose undergraduates to the use of quantitative methods for biological, environmental, and medical research.<br><a href="https://www.hsph.harvard.edu/biostatistics/diversity/summer-program/eligibility-application/" target="_blank" rel="noreferrer noopener external">Consider applying and note the requirements here!</a>', 'teamup', '2193528', '2016-11-21T00:00:00', '2016-11-21T23:59:00', 2, 0),
(280, 'Columbus Zoo Wildlights', '', 'Come see the Columbus Zoo Wildlights with other Arts and Sciences Scholars Programs. Admission to the zoo is free, <em>if you bring along 5 canned food items</em> to donate to the Mid-Ohio Foodbank. <strong>Meet at 4:00pm in front of Baker East</strong> to ride a CABS bus. We are limited to 30 STEM EE Scholars, please <a href="https://docs.google.com/forms/d/e/1FAIpQLSeA__MCmJsYM88G9cv75Synf9hmkRzy_4WYq9XrfgWRdE6Hhw/viewform" target="_blank" rel="noreferrer noopener external">RSVP</a>.', 'teamup', '2155517', '2016-11-18T16:00:00', '2016-11-18T20:30:00', 2, 0),
(279, 'Modeling and State Implementation of Regulatory Measures for Ohio''s Air Quality', 'Smith Lab, 3150', '<em>For student interested in the environmental regulation, public health and statistical models</em><br>The Ohio Environmental Protection Agency is a<strong> State Agency dedicated to protecting the environment and public health</strong> by ensuring compliance with environmental laws and demonstrating leadership in environmental stewarship.', 'teamup', '2155517', '2016-11-18T15:00:00', '2016-11-18T16:00:00', 2, 0),
(278, 'Healthy Places: Designing Cities for Walking and Biking', 'Thompson Library, 165 ', '<em>Students interested in Technology, Engineering and Mathematics </em><br>The Columbus Collaboratory will share some of the <strong>cutting edge technologies in development for their member companies,</strong> including a demo of CognizeR, the package developed for integrating IBM’s Watson into R.A panel on how Columbus and other cities are working to improve livability and encourage active transportation will feature speakers from the College of Engineering, Mid-Ohio Regional Planning Commission, Columbus Public Health, and YayBikes! Topics to include the use of mobility data and research to inform public policy decisions. A light meal will be served.', 'teamup', '2155517', '2016-11-18T11:45:00', '2016-11-18T13:00:00', 2, 0),
(277, 'H&S Fall Fest', 'Honors & Scholars Kuhn House', 'This year''s HSPB Fall Fest, at the Honors &amp; Scholars Kuhn House, will be held from 7:00 to 9:00 p.m. on November 17! Come to Fall Fest to learn about fall traditions around the world, enjoy free food, make thanksgiving door-decorations for Nationwide Children''s Hospital, and more! Bring your friends, and we''ll see you there!', 'teamup', '979004', '2016-11-17T19:00:00', '2016-11-17T21:00:00', 2, 0),
(275, 'ACMW: CS Technical Interview Workshop', 'Dreese 264', '<em>This event is recommended for computer science majors</em><br>Attend this ACMW (Association of Machinery-Women''s Chapter) workshop to sharpen your interview skills and gain valuable insight about the internship application process. Hear from past interns at Google, Microsoft, and local Columbus tech companies!', 'teamup', '2155517', '2016-11-16T19:00:00', '2016-11-16T20:00:00', 2, 0),
(276, 'A Career in National Labs', 'Physics Research Building', 'Learn more about diverse career paths in the STEM disciplines from Ohio State alumni working in industry. <a href="http://cem.osu.edu/files/2016/08/CEM-Alumni-Career-Series-Sergei-Manuilov-3M.jpg" target="_blank" rel="noreferrer noopener external">Click here for more info.</a>', 'teamup', '2155517', '2016-11-17T11:30:00', '2016-11-17T12:30:00', 2, 0),
(274, 'OUAB Flicks for Free, ft. Snowden', 'Ohio Union, U.S. Bank Conference Theater', 'First show: 6 PM<br>Second show: 8:30 PM<br>Free popcorn and beverages will be provided!<br><em>Disillusioned with the intelligence community, top contractor Edward Snowden (Joseph Gordon-Levitt) leaves his job at the National Security Agency. He now knows that a virtual mountain of data is being assembled to track all forms of digital communication -- not just from foreign governments and terrorist groups, but from ordinary Americans. When Snowden decides to leak this classified information, he becomes a traitor to some, a hero to others and a fugitive from the law.</em>', 'teamup', '836635', '2016-11-16T18:00:00', '2016-11-16T22:00:00', 2, 0),
(272, 'Preparing Papers', 'Dennis Learning Center', 'For this workshop, you will learn how to <strong>create strong thesis statements, introductions, body paragraphs and conclusions</strong> for any paper you have to write. You will learn how to combat writer’s block. We also will train you how to appropriately document supporting materials and avoid plagiarism at all costs.<br>To register for this event, click <a href="http://fye.osu.edu/successseries.html" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-11-16T10:30:00', '2016-11-16T11:15:00', 2, 0),
(273, '2nd Year Scholars Monthly Meeting (Make-Up Meeting)', 'Mendenhall Lab 115', 'Capstone Project Hours Log<br><a href="https://osu.az1.qualtrics.com/jfe/form/SV_882L66zhKtdQACx" target="_blank" rel="noreferrer noopener external">https://osu.az1.qualtrics.com/jfe/form/SV_882L66zhKtdQACx</a>', 'teamup', '2155500', '2016-11-16T16:00:00', '2016-11-16T17:30:00', 2, 0),
(271, 'Workshop: Social Media Mining', 'Hitchcock 031', '<em>This event will be useful for students in math and engineering, particularly CSE/CIS and Data Analytics.</em><br>A workshop demonstrating the use of<strong> Python to scrape data from Twitter and Facebook</strong> and as a general web scraping tool. Attendees can watch or follow along through the process. All scripts and instructions will be shared beforehand.<br> ', 'teamup', '2155517', '2016-11-15T19:30:00', '2016-11-15T21:00:00', 2, 0),
(270, 'Navigating the Internship Application Process', 'Macquigg Laboratory 264', '<em>This event is recommended for students interested in summer internships, with a particular focus on engineering and arts &amp; sciences.</em><br>Second years Alice Li and Stephen Wu will be talking about the <strong>internship application process</strong>. Learn how to set yourself apart from other applicants, get ahead in the job search, and get tips about the process. Topics include: side projects, resumes, career fairs, interviews, technical and behavorial questions, and healthy expectations. <br>Alice is a second year Actuarial Science and Computer Information Science major; Stephen is a Computer Science Engineering major. Learn about some of their experiences in applying to over 70 places, attending 5 career fairs, and interviewing and interacting with various employers. ', 'teamup', '836634', '2016-11-15T16:10:00', '2016-11-15T17:15:00', 2, 0),
(269, 'Udall Scholarship Informational Session', 'Kuhn Honors & Scholars House', 'The Udall Scholarship awards $7,000 to recognize outstanding<strong> sophomores and juniors committed to careers related to the environment, or to Native American students pursuing careers related to tribal policy/tribal health care</strong>. Forty scholarships will be awarded in the environmental category; twenty scholars will be selected for students passionate about Indian country. Successful applicants will not only have plans to become environmental or tribal leaders, but will have already begun demonstrating this commitment through related activities, research, academics, and job/internship experience. At this info session, we will discuss the Udall program, scholarship application, and selection process and criteria. Students interested in Ohio State''s nomination for the Udall must submit a campus application by February 13, 2017. More information can be found on the Udall''s website, http://<a href="http://www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx" target="_blank" rel="noreferrer noopener external">www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx</a>.<br>Two sessions will be held this week: 11/15 4-4:30PM and 11/18 2-2:30PM ', 'teamup', '2193528', '2016-11-15T14:00:00', '2016-11-15T14:30:00', 2, 0),
(268, 'Translational Data Analytics Forum Poster Session', 'Blackwell Inn and Conference Center ', '<em>This event is recommended for data analytics and actuarial science majors. </em><br>Ohio State postdoctoral researchers, graduate and undergraduate students, faculty, and staff present on their data analytics and decision science research. This is a unique opportunity to talk about research, meet others working the area of analytics and data science, and connect with potential collaborators across campus.', 'teamup', '2155517', '2016-11-14T13:00:00', '2016-11-14T15:00:00', 2, 0),
(267, 'Honda Guest Lecture: Vehicle Development Process, Geometric & Structural Digital Design', 'E100 Scott Lab', 'This discussion will briefly cover Honda’s overall development flow and the digital tools used to design a vehicle. The complexity of such systems requires multiple design iterations first between Styling and Body Design groups and then between Body Design and Manufacturing Groups. Full digital representations of vehicles enables critical and rapid communications within Honda between Styling, Design and Manufacturing.  The lecture will discuss project data management, good digital modeling and best practices for geometric modeling of vehicle body structures and flexible parametrics in the design process.', 'teamup', '2155517', '2016-11-14T12:40:00', '2016-11-14T13:40:00', 2, 0),
(266, 'Military Mental Health Symposium ', 'Ohio Union’s U.S. Bank Conference Theater', '<em>For students interested in health sciences and psychology</em><br>General Mark Graham (Ret.) and Carol Graham will share their story, which is featured in the book The Invisible Front: Love and Loss in an Era of Endless War. This military family is dedicated to addressing the <strong>military’s mental health crisis</strong> after losing both their sons in military service — one in combat and one to suicide. The event also includes a book signing and panel discussion. ', 'teamup', '2155517', '2016-11-14T09:00:00', '2016-11-14T12:00:00', 2, 0),
(265, 'Honors & Scholars Autumn Enrichment Grant', '', 'Working toward the Honors &amp; Scholars mission of providing students the ability to participate in opportunities that help create a holistic learning experience, the Honors &amp; Scholars Center will award $100,000 annually in student enrichment grants thanks solely to donor contributions. The scholarship amount will range based on the student''s proposals, with a maximum award of $3,000, and will be awarded through a competitive application process. <br>Funds are available to undergraduate Honors and Scholars students of all majors and can be utilized for a variety of purposes, including, but not limited to research, creative work and study abroad. Applicants must be current, full-time undergraduate students at the Columbus campus, and be in good standing in the University Honors Program or an Ohio State Scholars Program. The project or experience must enhance a student''s academic experience and learning, and take place before they graduate. The experiences will need to highlight and include the Honors &amp; Scholars <a href="http://honors-scholars.osu.edu/documents/goals.pdf" target="_blank" rel="noreferrer noopener external">G.O.A.L.S</a>,: Global awareness, Original inquiry, Academic enrichment, Leadership development and Service engagement.<br><strong><a href="https://hsapp.osu.edu/student_enrichment_grants/" target="_blank" rel="noreferrer noopener external">Click here to apply for the Autumn Enrichment Grant Competition</a> before November 25th!</strong>', 'teamup', '2193528', '2016-11-14T00:00:00', '2016-11-14T23:59:00', 2, 0),
(262, 'Football @ Maryland', '', 'null', 'teamup', '836635', '2016-11-12T15:30:00', '2016-11-13T18:30:00', 2, 0),
(263, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-11-12T19:00:00', '2016-11-12T21:00:00', 2, 0),
(264, 'Science Sundays: Sian Block on "How to perform your best under stress"', 'Ohio Union, U.S. Bank Conference Theatre', 'In an energetic tour of the latest brain science, Sian Beilock explains why we all too often blunder when the stakes are high. She reveals what happens in our brain and body when we experience performance anxiety and shows us how to succeed brilliantly when it matters most. Sian Beilock, psychology professor and director, Human performance Lab, University of Chicago, is author of the bestseller, Choke.<br><a href="https://stemoutreach.osu.edu/events/science-sundays-sian-block-how-perform-your-best-under-stress" target="_blank" rel="noreferrer noopener external">The lecture will be from 3 to 4 pm, in the Ohio Union U.S. Bank Conference Theatre. A reception will follow from 4 to 5 pm, in the Ohio Union Ohio Staters Traditions Room.</a>', 'teamup', '2155517', '2016-11-13T15:00:00', '2016-11-13T16:00:00', 2, 0),
(260, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-11-11T19:00:00', '2016-11-11T21:00:00', 2, 0),
(261, 'Maryland Football Watch / Tailgate Party', 'Houston House, TBD', 'Come out and enjoy an afternoon watching the Buckeyes crush Maryland on November 12th from 3:00pm-7:30pm! We will also have crafts, face painting, and board games! Pizza and refreshments will be provided.<br>Please <a href="https://www.surveymonkey.com/r/3MS9RWT" target="_blank" rel="noreferrer noopener external">RSVP and let us know what pizza, drinks, or games you would like</a>! Feel free to bring stuff to do as well. ', 'teamup', '2155517', '2016-11-12T15:00:00', '2016-11-12T20:00:00', 2, 0),
(258, 'Veteran''s Day - No Classes', '', 'No classes, offices closed.', 'teamup', '836635', '2016-11-11T00:00:00', '2016-11-11T23:59:00', 2, 0),
(259, 'Data Science Workshop', '', '<em>This two-day seminar is for students interested in data analytics and will provide the essentials of data science in the finance industry and python programming. This event is recommended for CSE/CIS, Data Analytics, and Actuarial Science majors. </em><br>DATES: 12 – 13 November 2016 <br>COURSE LENGTH: 2 days <br>TIME: 09:30am – 5:00pm each day<br>$149 per ticket, using discount code: BuckeyesIDS2016. <br>The Big Data &amp; Analytics Association will soon be hosting Cognitir, a world-renown company originally founded in Europe. They will hold a workshop on the analytics and <strong>data science in Finance</strong>. This is a 2-day weekend event (<strong>Nov 12 &amp; 13) </strong>which will result in a <strong>Python certification</strong>. <br>To learn more, visit <a href="http://www.cognitir.com/osu/ids-finance" target="_blank" rel="noreferrer noopener external">http://www.cognitir.com/osu/ids-finance</a>  or click <a href="https://gallery.mailchimp.com/0724670675ea259cb94841576/files/Finance_Analytics_Workshop_BDAA_Cognitir.pdf" target="_blank" rel="noreferrer noopener external">here</a> for the syllabus.', 'teamup', '2155517', '2016-11-12T00:00:00', '2016-11-13T23:59:00', 2, 0),
(257, 'Gearing Up for Higher Ed', 'Dennis Learning Center', 'The gearing up for higher education workshop was developed to help you know what it really takes to succeed in college. It will help you apply <strong>strategies for managing time, learning from texts and lectures and preparing for exams</strong> that will help you thrive in the context of a university.<br>To register for this event, click <a href="http://fye.osu.edu/successseries.html" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-11-10T15:00:00', '2016-11-10T15:45:00', 2, 0),
(256, 'OUAB Flicks for Free: ft. War Dogs', 'Ohio Union, U.S. Bank Conference Theater', 'First show: 6 PM<br>Second show: 8:30 PM<br>Location: U.S. Bank Conference Theater (Ohio Union)<br>Free popcorn and beverages will be provided!<br><em>Two friends in their early 20s (Hill and Teller) living in Miami Beach during the Iraq War exploit a little-known government initiative that allows small businesses to bid on U.S. Military contracts. Starting small, they begin raking in big money and are living the high life. But the pair gets in over their heads when they land a 300 million dollar deal to arm the Afghan Military - a deal that puts them in business with some very shady people, not the least of which turns out to be the U.S. Government. Based on true events.<em></em></em>', 'teamup', '836635', '2016-11-09T20:30:00', '2016-11-09T22:00:00', 2, 0),
(255, 'OSU Graduate and Professional School Fair', 'Ohio Union Great Hall Meeting Rooms 1, 2 and 3', 'The seventh annual OSU Graduate and Professional School Fair will be held on Wednesday, November 9 in the Ohio Union Great Hall Meeting Rooms 1, 2 and 3. Admission representatives from more than twenty OSU programs, pre-law and pre-health advisors, and arts and sciences career counselors will be available to answer questions. This is a good opportunity for students who are approaching graduation to learn what they need to do in order to apply to an OSU program. It is also a great opportunity for students who are new to OSU to begin to think about coursework, extracurricular activities, and co-curricular opportunities that will help them to prepare for graduate or professional school admission. This Fair is an option for Student Success Series credit. Admission is free and refreshments will be provided. This program is presented by the College of Arts and Sciences Student Council.', 'teamup', '836635', '2016-11-09T16:30:00', '2016-11-09T18:30:00', 2, 0),
(254, '2nd Year Scholars Monthly Meeting', 'Mendenhall Lab 115', 'Please come with an<strong> updated version of your resume and/or CV</strong> and a<strong> draft introductory paragraph</strong> for your 2nd year project. See the previous email for more details. <br>Capstone Project Hours Log: <a href="https://osu.az1.qualtrics.com/jfe/form/SV_882L66zhKtdQACx" target="_blank" rel="noreferrer noopener external">https://osu.az1.qualtrics.com/jfe/form/SV_882L66zhKtdQACx</a>', 'teamup', '2155500', '2016-11-09T16:00:00', '2016-11-09T17:30:00', 2, 0),
(253, 'Byrd Polar Lecture: Global Climate Change', 'Macquigg Laboratory 264', 'The Byrd Polar and Climate Research Center (BPCRC) at <a href="http://www.osu.edu/" target="_blank" rel="noreferrer noopener external">The Ohio State University</a> is recognized internationally as a leader in polar, alpine, and climate research. Our research programs are conducted throughout the world. The Center is named in honor of <a href="http://library.osu.edu/find/collections/byrd-polar-archives/byrd/" target="_blank" rel="noreferrer noopener external">Admiral Richard E. Byrd</a>, America''s most famous polar explorer. There are <a href="http://bpcrc.osu.edu/groups" target="_blank" rel="noreferrer noopener external">ten research groups</a> at BPCRC, along with a Library, <a href="http://library.osu.edu/find/collections/byrd-polar-archives" target="_blank" rel="noreferrer noopener external">Archival Program</a>, the <a href="http://research.bpcrc.osu.edu/rr/" target="_blank" rel="noreferrer noopener external">Polar Rock Repository</a>, and a team of support staff. Research at the Center focuses on the role of cold regions in the Earth''s overall climate system, and encompasses geological sciences, geochemistry, glaciology, paleoclimatology, meteorology, remote sensing, ocean dynamics, and the history of polar exploration.<br>Today, the Byrd Polar Center will be lecturing about global climate change!', 'teamup', '836634', '2016-11-08T16:10:00', '2016-11-08T17:15:00', 2, 0),
(252, 'Inside Graduate Admissions: Merit, Diversity, and Faculty Gatekeeping', '1080 Physics Research Building - Smith Seminar Room ', 'How does graduate admissions work? Who does the system work for, and who falls through its cracks? Where does admissions reform fit into broader efforts to reduce inequalities in graduate education? In this talk, education professor Julie Posselt will pull back the curtain on admissions processes usually conducted in secret, and examine the limits and possibilities of rethinking admissions for increasing diversity in STEM. Drawing on more than five years of research that includes extensive observations of admission committees in action, Posselt will reveal how professors create and negotiate the meaning of merit as they evaluate applicants and work daily with their students. She will also show how departments that improve diversity through admissions and recruitment, but that lack strong mentoring relationships, may struggle to maintain gains serving underrepresented populations.', 'teamup', '2155517', '2016-11-08T16:00:00', '2016-11-08T17:00:00', 2, 0),
(251, 'Co-op Internship Research (CIR)', 'Caldwell Lab (Room 109)', '<em>This event is highly recommended for students in Biological and Chemical Science related areas and Mathematical and Engineering related areas.</em><br>Join the OHSE CIR Session and learn from OHSE scholars co-op, internship and research experiences. There will be t<strong>wo session and students may schoose wich to attend</strong>.<br>Agenda:<br />3:45-4:45 Biological and Chemical Sciences related areas<br />4:45-5:00 Break/Refreshments<br />5:00-5:45 Mathematical and Engineering related areas<br />5:45-6:00 Q&amp;A', 'teamup', '2155517', '2016-11-08T15:45:00', '2016-11-08T18:00:00', 2, 0),
(250, 'Redefining the Path to Health Equity', 'Mershon Auditorium', '<em>The Provost''s Discovery Themes Lecture Program is recommended for all students.</em><br>David Satcher, MD, PhD, is the second person in history to simultaneously hold the positions of <strong>US Surgeon General and Assistant Secretary for Health</strong>. In these dual roles, he encouraged public debate about the importance of a balanced healthcare system and a wide range of related topics, including mental health, suicide, cloning, sex education and AIDS. Serving under both President Bill Clinton and President George H.W. Bush, he led efforts to eliminate racial and ethnic disparities in health.<br>To register, click <a href="http://discovery.osu.edu/about/provosts-discovery-themes-lecturer-program/david-satcher.html" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-11-08T15:30:00', '2016-11-08T16:45:00', 2, 0),
(249, 'Professional Development Workshop: Professional Small Talk & Networking', 'Student Alumni Council Room, Ohio Union', 'This workshop will teach student about the Power of the 3 Ps: Power, Presence and Perception and how to become more effective, engaged, and connected leaders. It’s not about collecting business cards. It’s about caring for others and establishing genuine connections. At the close of the event, participants will receive additional resources created by industry experts for continued development opportunities.<br>Facilitated by: Kwame Christian, Director of Community Relations Kirwan Institute on Race and Ethnicity<br>Kaylee Hartman<br>Student Activities - OUAB Grad/Prof <br><a href="mailto:hartman.557@osu.edu" target="_blank" rel="noreferrer noopener external">hartman.557@osu.edu</a><br>614-292-1274', 'teamup', '836635', '2016-11-08T12:00:00', '2016-11-08T13:00:00', 2, 0),
(248, 'Election Day', '', 'Go vote and make your voice heard! If you are registered in Franklin County, polls will be open from 6:30 am to 7:30 pm at the Ohio Union.<br>Be sure to be educated about your choices through resources like the ones below: <br><a href="http://onyourballot.vote411.org/index.do" target="_blank" rel="noreferrer noopener external">On Your Ballot</a>, <a href="https://votesmart.org/" target="_blank" rel="noreferrer noopener external">VoteSmart</a>, <a href="https://ballotpedia.org/Main_Page" target="_blank" rel="noreferrer noopener external">Ballotpedia</a>', 'teamup', '836635', '2016-11-08T00:00:00', '2016-11-08T23:59:00', 2, 0),
(247, 'HSPB Trivia Night', 'Curl Market Viewpoint North', 'This month''s board will focus on topics in the <strong>presidential election process</strong>, so come prepared! Students from any Honors or Scholars group are welcome, and you are not required to come with a team, but space is limited, so please <a href="http://r20.rs6.net/tn.jsp?f=001MaJJupA-3MsVFTe_K38rI56FHXV3-iq_0Hjs0zpBvyX5eRuYKQyp4PtJhyhcnZRymLX-OWprIdK072zFdUumYME1h0QvSTZJdXl0ZWkfnNRmAKzWuiduyoP4ESg75FCuB23NE7OYxg7rKhX1ecTOsniG-eycWWcz1RC9L7FdmmI=&amp;c=xG3Ei_FDrgAMqTlDbxIrhMz9Sqpw0c1JDkNNfRFojy5kaWHTTocPOg==&amp;ch=sw5VYlLKwJsdFGOJH4krtYiVQxNwHZ-K12FAj5rQ52GvuQG-QjC6ew==" target="_blank" rel="noreferrer noopener external">RSVP </a>.', 'teamup', '979004', '2016-11-07T18:30:00', '2016-11-07T20:00:00', 2, 0),
(245, 'The Case of the Missing Ribosome and Other Tales of Protein Translation', 'BRT 115 ', '<em>For students interested in the biological sciences</em><br>As part of its Host Pathogen Seminar Series, the Center for Microbial Interface Biology — along with co-sponsors <strong>Department of Microbial Infection and Immunity</strong>, Center for Retrovirus Research and Discovery Themes in Infectious Disease — will host Dr. Jonathan Yewdell, chief of the cellular biology section, Laboratory of Viral Diseases, NIAID, NIH. ', 'teamup', '2155517', '2016-11-07T16:00:00', '2016-11-07T17:00:00', 2, 0),
(246, 'Minority in Engineering Panel', 'Baker 144', 'Come listen to panelists Lisa Abrams, Latonia Stiner-Jones, and Alex Avendañoanswer your questions about what it''s like to be a minority in engineering and how to successfully navigate any obstacles you may face. Dinner will be provided so please RSVP below by Wednesday November 2nd!<br><a href="https://goo.gl/forms/kzkrgPa7QJ1FTs122" target="_blank" rel="noreferrer noopener external">https://goo.gl/forms/kzkrgPa7QJ1FTs122</a>', 'teamup', '2155517', '2016-11-07T18:30:00', '2016-11-07T20:00:00', 2, 0),
(243, 'Football vs Nebraska', '', 'null', 'teamup', '836635', '2016-11-05T20:00:00', '2016-11-05T23:45:00', 2, 0),
(244, 'Scholarship America Dream Award (For Sophomores and Up)', '', 'The Dream Award is Scholarship America’s renewable scholarship program for financially needy students who have overcome barriers and have successfully started their college education. Awards were made to students selected from across the nation who are entering their <strong>second year or higher of education beyond high school</strong>; the scholarships are both renewable and increase in amount each year. Scholarship America provides Dream Awards ranging from $5,000 to $15,000 based on the individual student’s financial need. Each student’s award will increase by $1,000 each year to help them successfully finish school and earn their degrees.<br>Dream Award scholarships for 2017-18 will include general scholarships, STEM-specific scholarships (for study in science, technology, engineering and math-related majors) and the World Journal Dream Award Scholarship for Chinese American students. Financial need will always be considered in determining award amounts.', 'teamup', '2193528', '2016-11-07T00:00:00', '2016-11-07T23:59:00', 2, 0),
(241, 'De-stress Canvas Painting Night', 'Houston House Art Room', 'Come out and enjoy a night of canvas painting with your mentors!<br>There will be pizza and supplies, all you need is a creative imagination!<br>Please RSVP through the link provided, by Thursday October 27th, to ensure we have enough supplies and food. <a href="https://www.surveymonkey.com/r/X9NN88T" rel="noreferrer noopener external">https://www.surveymonkey.com/r/X9NN88T</a>', 'teamup', '836634', '2016-11-04T18:00:00', '2016-11-04T20:00:00', 2, 0),
(242, 'Web Workshop with Rockwell Automation', '260 Dreese Labs', '<em>This event is recommended for any students with interest in programming, including beginners. </em><br>Web Workshop with automation with React, Particle Photons, and Particle Cloud<br>Rockwell Automation is organizing a web development workshop involving putting together a single pager web app via React that reads data from IoT devices and displays it. There will be pizza and some prizes will be given out. If interested, please RSVP at <a href="http://go.osu.edu/rockwell" target="_blank" rel="noreferrer noopener external">http://go.osu.edu/rockwell</a>.', 'teamup', '2155517', '2016-11-05T11:15:00', '2016-11-05T15:00:00', 2, 0),
(238, 'OUAB Karaoke Night', ' Woody''s Tavern', 'null', 'teamup', '836635', '2016-11-03T19:00:00', '2016-11-03T21:30:00', 2, 0),
(239, 'How to Get a Job Saving the Planet', 'Scott, E100 ', 'Event dedicated for STEM students with an interest in environment.<br>Breakfast will be provided to interested students. If interested RSVP by clicking <a href="http://go.osu.edu/egoodstein" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-11-04T09:00:00', '2016-11-04T10:00:00', 2, 0),
(240, 'Chemical Abstracts Service: Technology Open House ', '2540 Olentangy River Road', 'This is a great opportunity to learn more about CAS, networking and to consider CAS as a future employer whether it be an internship or fulltime employment, particularly for CSE/CIS/Data Analytics and related majors. Check out the details on this <a href="http://bdaaatohiostate.us12.list-manage.com/track/click?u=142665677fc58bf1a34031807&amp;id=1db7008830&amp;e=6066988315" target="_blank" rel="noreferrer noopener external">flyer.</a>', 'teamup', '2155517', '2016-11-04T10:00:00', '2016-11-04T17:00:00', 2, 0),
(237, 'Republicans, Democrats and Sustainability: Recovering Bipartisan Environmental Politics', 'Knowlton Hall, Room 205', '<em>For any student interested in the enviroment and politics.</em><br>Events are sponsored by The Sustainable and Resilient Economy and SUSTAINS Learning Community.<br> ', 'teamup', '2155517', '2016-11-03T19:00:00', '2016-11-03T20:00:00', 2, 0),
(235, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-11-02T20:00:00', '2016-11-02T22:00:00', 2, 0),
(236, 'Finding & Applying for Summer STEM Research Programs', 'Page Hall, 60', 'There are multitudes of<strong> national and international research programs for students in the STEM</strong> (Science, Technology, Engineering, and Mathematics) fields during the summer. Attend this session to learn what is out there and how to find programs, what is required to apply, and get insight and tips for a successful application from previous participants in summer undergraduate research programs.', 'teamup', '979004', '2016-11-03T17:30:00', '2016-11-03T18:30:00', 2, 0),
(234, 'Science Cafe: The Science of Election Prediction', '18th Avenue Library: Research Commons (3rd Floor)', '<em>This event will best suited for math and computer science majors</em><br><strong>Comparing election forecasting models</strong>, election stock markets, polls-of-polls, and other prediction systems for the 2016 U.S. presidential election. How should the quality of a prediction system be assessed? Which prediction systems have been most successful in the past? How useful can these predictions be in this most unpredictable election year?', 'teamup', '2155517', '2016-11-02T18:30:00', '2016-11-02T19:30:00', 2, 0),
(232, 'Pre-Law Forum - Legal Careers Panel', 'Moritz College of Law, Saxbe Auditorium', '<em>Students interested in law-school</em><br>This is a great opportunity to hear from <strong>practicing attorneys</strong> about different areas of law and things to consider as you figure out what sort of attorney you may want to be. Be sure to ask questions regarding STEM and law.', 'teamup', '2155517', '2016-11-02T18:00:00', '2016-11-02T19:15:00', 2, 0),
(233, 'OUAB Flicks for Free ft. The Jungle Book', 'Ohio Union, U.S. Bank Conference Theater', '<em>The man-cub Mowgli flees the jungle after a threat from the tiger Shere Khan. Guided by Bagheera the panther and the bear Baloo, Mowgli embarks on a journey of self-discovery, though he also meets creatures who don''t have his best interests at heart. </em>', 'teamup', '836635', '2016-11-02T18:00:00', '2016-11-02T20:00:00', 2, 0),
(231, 'Professional School Information Night ', '', '<em>This event is for Second- and Third-Year Scholars interested in Professonal Schools</em><br> <br>The Biological Sciences, Health Sciences and STEM EE Scholars programs are collaborating to offer a <strong>Professional School Information Night</strong> to the upper-class scholars. In order to deliver an all-encompassing program, we will be offering multiple break-out sessions, so students can attend at least two professional schools’ presentations.<br> <br>To RSVP, click <a href="https://goo.gl/forms/TYx1r5IVAQ7J7gJj2" target="_blank" rel="noreferrer noopener external">here</a>.<br> ', 'teamup', '2155500', '2016-11-02T17:00:00', '2016-11-02T18:30:00', 2, 0),
(230, 'Columbus Collaboratory Tech Talk', 'Hitchcock, 031', '<em>If you are familiar with the statistical platform R, this event will be interesting for you.</em><br>The Columbus Collaboratory will share some of the cutting edge technologies in development for their member companies, including a <strong>demo of CognizeR</strong>, the package developed for integrating IBM’s Watson into R.', 'teamup', '2155517', '2016-11-01T19:30:00', '2016-11-01T21:00:00', 2, 0),
(229, 'HSPB Buckeyes and Batons', 'Taylor Tower Lobby', 'Honors &amp; Scholars Board presents Buckeyes &amp; Batons: a clinic focused on baton twirling and leadership development. Come and join this collaboration between the Buckeye Twirl team and the Honors &amp; Scholars Programming Board on Tuesday, November 1 from 6:00 to 7:30 p.m. in Taylor Tower''s Lobby. Buckeye Donuts will be provided and no previous twirling experience or materials required--we will teach you all that you need to know! Wear something comfortable to move around in. Please state your interest by emailing <a href="mailto:hspb@osu.edu" target="_blank" rel="noreferrer noopener external">hspb@osu.edu</a>.', 'teamup', '979004', '2016-11-01T18:00:00', '2016-11-01T19:30:00', 2, 0),
(227, 'Dental Student Panel', 'Jennings 40 ', '<em>Event geared towards students interested in Dental School</em><br> <br><strong>Students in dental school</strong> will give their perspective and advice to undergraduate students pursuing a career in dentistry. RSVVP to Melissa Basford, Bio Sci Scholars, at basford.18@osu.edu.', 'teamup', '2155517', '2016-11-01T13:00:00', '2016-11-01T17:15:00', 2, 0),
(228, 'Arts & Sciences Career Services Resume Tips', 'Macquigg Laboratory 264', '<em>This event is recommended for students of all majors interested in resume tips</em><em>.</em><br>Bring a current version of your resume!', 'teamup', '836634', '2016-11-01T16:10:00', '2016-11-01T17:05:00', 2, 0),
(225, 'H&S Halloween Bash with Best Buddies', '', 'Are you excited to celebrate Halloween? Are you ready to wear your best costume and make some fun halloween crafts with some new friends? Then come to HSPB''s Halloween Bash with Best Buddies! Best Buddies is a student organization that works to link OSU students with students with a range of intellectual and developmental disabilities to form the best friendships. At this event, you will get the chance to learn more about the Best Buddies organization and have a halloween themed craft party with the members of the Best Buddies organization where you will make some halloween capes together. But space is limited so RSVP at <a href="https://goo.gl/forms/xZDNWknQdkH7kPil2" target="_blank" rel="noreferrer noopener external">https://goo.gl/forms/xZDNWknQdkH7kPil2</a> for more information about the event and the location.', 'teamup', '979004', '2016-10-31T18:30:00', '2016-10-31T20:30:00', 2, 0),
(226, 'Halloween Week Star Party', 'Roof of Smith Lab, access by stairs from planetarium, Smith Lab 5033', 'Attendees will be pointing out stars and the constellations, taking a look at Mars and Saturn and other sights through the telescopes.Cancelation of Roof Night may be due to weather and will be announced by 5pm for that day. The information will be posted on OSU Planetarium''s <a href="https://www.facebook.com/OSUPlanetarium/" target="_blank" rel="noreferrer noopener external">Facebook page</a>.', 'teamup', '2155517', '2016-10-31T19:00:00', '2016-11-02T21:00:00', 2, 0),
(223, 'American Institute of Aeronautics and Astronautics Scholarships', '', 'The AIAA Foundation annually awards financial aid through a <a href="http://www.aiaa.org/scholarshipsandawards/" target="_blank" rel="noreferrer noopener external">number of scholarships</a> to undergraduate and graduate students in science or engineering programs. These scholarships are particularly for those in aerospace-related majors, but the criteria are pretty broad.', 'teamup', '2193528', '2016-10-31T00:00:00', '2016-10-31T23:59:00', 2, 0),
(224, 'SOLAR Foundation Undergraduate Research Awards', '', 'Recommended for undergraduate students pursuing <strong>research in the fields of epidemiology, virology, HIV and AIDS education, and other infections of the blood and related subjects</strong>.<br>The application is due <strong>Friday (12/2)</strong>. Read more at http://go.osu.edu/solarfund.', 'teamup', '2193528', '2016-10-31T00:00:00', '2016-10-31T23:59:00', 2, 0),
(222, 'Women Transportation Seminar Sharon D. Memorial Scholarship', '', 'This scholarship is recommended for <strong>females in their second-year and up in engineering and other fields related to transportation</strong>.<br>Sharon D. Banks Memorial Scholarship (Undergraduate): Local Award - $1,000, National Award - $5,000<br><a href="https://gallery.mailchimp.com/0724670675ea259cb94841576/files/WTS_Scholarship_Letter_2016.pdf" target="_blank" rel="noreferrer noopener external">Deadine: November 11, 2016</a>', 'teamup', '2193528', '2016-10-31T00:00:00', '2016-10-31T23:59:00', 2, 0),
(216, 'Residence Life Kickball Tournament (STEM Team)', 'Lincoln Tower Park Fields', 'Registration Information: There will be 9-12 players per team and up to 10 players on the field per inning. Each team must have at least 4 female players. Students interested contact Alex Orkis (<a href="mailto:orkis.6@buckeyemail.osu.edu" target="_blank" rel="noreferrer noopener external">orkis.6@buckeyemail.osu.edu</a>).', 'teamup', '2155517', '2016-10-28T00:00:00', '2016-10-28T23:59:00', 2, 0),
(217, 'Refining Opioid Receptor Signaling to Promote Analgesia and Avoid Side Effects', 'L035 James, Wasserstrom Family Conference Room', 'null', 'teamup', '836634', '2016-10-28T14:00:00', '2016-10-28T15:00:00', 2, 0),
(218, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-10-28T19:00:00', '2016-10-28T21:00:00', 2, 0),
(219, 'Houston-Hauck Hall Council Presents: Pumpkin Carving Contest', 'Houston Art Room', 'Prizes for funniest, scariest, and most school spirit!', 'teamup', '836635', '2016-10-28T20:00:00', '2016-10-28T21:00:00', 2, 0),
(220, 'Football vs Northwestern', '', 'Make some time to watch this game', 'teamup', '836635', '2016-10-29T15:30:00', '2016-10-29T19:30:00', 2, 0),
(221, 'Generation Google, Google Lime, Women Techmakers Scholarships', '', '<em>The three scholarships below are for computer science majors and related degrees (this includes ECE, CE, and Data Analytics).</em><br><ul><br><li><br><strong><a href="http://ohio-state.us11.list-manage.com/track/click?u=9984bd1eae9eb3104355b9c94&amp;id=a6658246db&amp;e=bb0af33337" target="_blank" rel="noreferrer noopener external">Women Techmakers Scholars Program</a></strong> (formerly known as the Google Anita Borg Memorial Scholarship) is open to current female undergraduate or graduate students who will be studying at a university in the United States or Canada for the 2017-2018 academic year. <strong>Deadline: December 1, 2016</strong><br></li><br><li><br><strong><a href="http://ohio-state.us11.list-manage2.com/track/click?u=9984bd1eae9eb3104355b9c94&amp;id=88ac5847b9&amp;e=bb0af33337" target="_blank" rel="noreferrer noopener external">Generation Google Scholarship</a></strong> is open to current undergraduate or graduate students from an underrepresented background in computer science who will be studying at a university in United States or Canada for the 2017-2018 academic year.  <strong>Deadline: December 1, 2016</strong><br></li><br><li><br><strong><a href="http://ohio-state.us11.list-manage.com/track/click?u=9984bd1eae9eb3104355b9c94&amp;id=44cd14b247&amp;e=bb0af33337" target="_blank" rel="noreferrer noopener external">Google Lime Scholarship</a></strong> is open to current undergraduate or graduate students with disabilities who will be studying at a university in United States or Canada for the 2017-2018 academic year. <strong> Deadline: December 4, 2016</strong><br></li><br></ul>', 'teamup', '2193528', '2016-10-31T00:00:00', '2016-10-31T23:59:00', 2, 0),
(215, 'OUABringing Home The Gold with Kayla Harrison', 'Ohio Union Performance Hall', 'OUAB is hosting 2016 Rio Gold Medalist &amp; Olympian in the sport of Judo, Kayla Harrison. Tickets are free, two per BuckID and are available at the Ohio Union Information Desk.<br> ', 'teamup', '836635', '2016-10-27T19:00:00', '2016-10-27T21:30:00', 2, 0),
(214, 'The Plough and the Stars', 'Southern Theater downtown', 'Open exclusively to Ohio State students at a special price of $10 per ticket.  <br><strong>The iconic Irish play,</strong> “The Plough and the Stars” is co-presented by The Ohio State University’s College of Arts and Sciences and the Columbus Association for the Performing Arts (CAPA) in honor of the 100th Anniversary of Ireland’s Easter Rising. Set amid the tumult of the Easter Rising, The Plough and the Stars is the story of ordinary lives ripped apart by the idealism of the time. The residents of a Dublin tenement shelter from the violence that sweeps through the city''s streets. A revolution that will shape the country''s future rages around them. What kind of Ireland awaits them? The Plough and the Stars was first performed at the Abbey Theatre in 1926. The audience rioted. Now regarded as a masterpiece, this provocative play is an essential part of our understanding of 1916. Olivier Award-winning director Sean Holmes brings a new perspective to Sean O''Casey''s absorbing play produced by Ireland’s own Abbey Theatre.<em><br></em><br><em>To attend, RSVP <a href="https://docs.google.com/forms/d/e/1FAIpQLSepe7doUkwNV66lvrVD7dE4j8Y5PgBaHOWAdXsYGjqC_LcABA/viewform?c=0&amp;w=1" target="_blank" rel="noreferrer noopener external">here</a>. Meet at the Ohio Union Bus Turnaround at 4:15pm to board the bus.</em>', 'teamup', '2155517', '2016-10-27T17:00:00', '2016-10-27T19:30:00', 2, 0),
(213, 'Big Data Law and Policy', 'Drinko Hall’s Saxbe Auditorium ', '<em>Event will be interesting for all STEM majors, and specifically helpful for students in Engineering, Techonology and Mathematics</em><br>Employing increasingly sophisticated algorithms and artificial intelligence technologies, businesses and governments are enthusiastically using big data to solve problems and create value. At the same time, individuals are increasingly worried about how massive data collection and analysis will impact their privacy, and whether companies and governments will use it fairly. <strong>Do we need ground rules to encourage the many benefits, and reduce the risks, of our new algorithmic society?</strong> If so, can government set such rules consistent with the First Amendment?<br>To register, click <a href="http://moritzlaw.osu.edu/registrations/event/sidley-austin-distinguished-lecture/" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-27T16:00:00', '2016-10-27T18:00:00', 2, 0),
(212, '2016 Health Sciences Majors Fair', 'Biomedical Research Tower, Room 115', '<em>For students interested in health sciences</em><br> <br>Meet representatives from the following (see below) health care-focused<strong> undergraduate and graduate/professional programs</strong>. To register, please click <a href="http://scarletandgray.osu.edu" target="_blank" rel="noreferrer noopener external">here</a>. and enter the access code “Health2016.”<br> <br>Applied Clinical and Preclinical Research <br>Athletic Training <br>Biomedical Science <br>Biophysics<br>Dental Hygiene<br>Dentistry <br>Health and Wellness Innovation in Health Care<br>Health Information<br>Management and Systems<br>Health Sciences <br>Law <br>Medical Dietetics <br>Medical Laboratory<br>Science <br>Medical Scientist Training Program <br>Medicine <br>Neuroscience <br>Nursing <br>Occupational<br>Therapy <br>Optometry <br>Pharmacy <br>Physical Therapy <br>Public Health <br>Radiologic Sciences and<br>Therapy <br>Respiratory Therapy <br>Social Work <br>University Exploration <br>Veterinary Medicine<br>UAP170020', 'teamup', '2155517', '2016-10-27T15:00:00', '2016-10-27T17:00:00', 2, 0),
(211, 'Wellness Workshop: Managing Relationships', 'Ohio Union, Barbie Tootle Room', 'Healthy relationships will be defined, stages of a relationship will be discussed, as well as role playing on ways to deal with differences and power struggles in a relationship. Participants will determine various issues that arise in relationships (i.e. jealousy) and working with the facilitator to think through these issues and options students may have in the particular situations. Lastly, we will be discussing how to maintain a healthy relationship.', 'teamup', '836635', '2016-10-27T12:00:00', '2016-10-27T13:00:00', 2, 0),
(210, 'Pre-Health Collegium Speaker', 'Hagerty 071', 'The Pre-Health Collegium will be hosting Dr. William Miller this Wednesday, October 26, at 6:30 pm. Dr. Miller, MD, PhD, MPH, is the current Chair of the College of Public Health and will be speaking about career options within medicine, experiences within his own career, and will be open for Q&amp;A. <a href="https://docs.google.com/forms/d/e/1FAIpQLSekDEtgryCrFclQp_y3lVY_sOgqBOugbOFpMVvbRxI7Fh8pFA/viewform" target="_blank" rel="noreferrer noopener external">RSVP preferred</a> but walk ins welcome!', 'teamup', '2155517', '2016-10-26T18:30:00', '2016-10-26T19:30:00', 2, 0),
(209, ' Flicks for Free ft. The Conjuring 2', 'Ohio Union, U.S. Bank Conference Theater', '<em>Free popcorn and beverages will be provided</em><br>In 1977, paranormal investigators Ed and Lorraine Warren travel to London, England, where single mother Peggy Hodgson believes that something evil is in her home. When Peggy''s youngest daughter starts showing signs of demonic possession, Ed and Lorraine attempt to help the besieged girl, only to find themselves targeted by the malicious spirits.<br> ', 'teamup', '836635', '2016-10-26T18:00:00', '2016-10-26T20:00:00', 2, 0),
(208, 'Coding Workshop: Introduction to Swift for iOS', 'OSU TechHub', '"Have you ever wanted to code for iOS but didn’t know quite where to start? As <a href="http://hack.osu.edu/" target="_blank" rel="noreferrer noopener external">Hack OHI/O</a> approaches we thought this would be a great opportunity to have one of our friends from Apple® visit and provide and introduction to Swift™ and X code®. This interactive workshop will go over the basics of creating an app for iPhone® or iPad®. It will occur in store on October 26 from 6:00- 8:00 p.m."<br>See <a href="https://techhub.osu.edu/news/2016/10/06/coding-workshop-introduction-swift-ios" target="_blank" rel="noreferrer noopener external">here</a> for more details. <a href="https://osu.az1.qualtrics.com/jfe/form/SV_3s1febZu43NEgw5" target="_blank" rel="noreferrer noopener external">RSVP</a> reqiured.', 'teamup', '2155517', '2016-10-26T18:00:00', '2016-10-26T20:00:00', 2, 0);
INSERT INTO `events` (`event_id`, `name`, `location`, `desc`, `source1`, `source2`, `time_start`, `time_end`, `importance`, `approved`) VALUES
(206, 'Men''s Soccer', 'Jesse Owens Memorial Stadium', 'null', 'teamup', '836635', '2016-10-26T00:00:00', '2016-10-26T23:59:00', 2, 0),
(207, 'Memory Tools for Effective Studying', 'Dennis Learning Center', 'The Memory Tools for Effective Studying workshop t<strong>eaches you the different types of memory and the factors that affect it, how to build meaningful learning and how to solidify that meaning for the long-term.</strong> By the end of the workshop, you will understand what it takes to not just study new information but to do so in ways to help you to truly retain it for both the day of the exam and long after.<br>To register for this workshop, click <a href="http://fye.osu.edu/successseries.html" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-26T15:00:00', '2016-10-26T15:45:00', 2, 0),
(205, 'Lean-In: Empowering Women in Technology', 'Dreese Lab 264', 'Join ACM-W''s next Lean In discussion on empowering women to achieve their dreams despite the challenges and gender biases in our workplace, classroom, and personal settings. Our members will also be chatting about our experiences at the Grace Hopper Celebration conference. *Food will be provided*', 'teamup', '2155517', '2016-10-26T00:00:00', '2016-10-26T23:59:00', 2, 0),
(204, 'Men''s Soccer', 'Jesse Owens Memorial Stadium', 'null', 'teamup', '836635', '2016-10-25T19:00:00', '2016-10-25T21:00:00', 2, 0),
(203, 'STEM Jeopardy', 'Macquigg Laboratory 264', 'Come and join the fun with your STEM EE friends at this weeks Tuesday Event: STEM EE Jeopardy! Encourage all of your STEM peers to come because we will be working in teams of 3-5 people to play our STEM spin on Jeopardy. This will be a good chance to take a break from Midterm studying to play a fun game! The categories will be Science, Technology, Engineering, Mathematics, and Engagement &amp; Exploration so it is best to have one member of your team from each STEM house. ', 'teamup', '836634', '2016-10-25T16:10:00', '2016-10-25T17:05:00', 2, 0),
(202, 'The Science-Journalism Duality: Behind the Scenes at Scientific American', '1080 Physics Research Building - Smith Seminar Room', 'How did a (mostly) contented grad student running geophysical convection simulations wind up as a gatekeeper between science and the public? In this talk I''ll try to give a sense of what motivates science writers and editors, what exactly it is that we do, how we are navigating the turbulence in the publishing industry, and what it all means for the broader scientific community. I''ll naturally focus on <em>Scientific American </em>and other publications I’ve worked for, but I''ll comment on broader trends and offer thoughts and tips of use not just for writing a magazine article, but for any other writing or communications project you take on. One of the thorniest issues that science journalists face is how to make sense of scientific disagreements and avoid pitfalls such as false balance. I''ll offer some remarks, but I''m also interested in your thoughts and advice for how we journalists might do better.', 'teamup', '2155517', '2016-10-25T16:00:00', '2016-10-25T17:00:00', 2, 0),
(201, 'Bettering the World with Liz Bohannon', 'Ohio Union Performance Hall', 'Upon graduating college (and at the same age as most of us) Liz uprooted herself and moved to Uganda to take part in something bigger than herself to empower the women there to continue education past high school and earn a degree of their own. To do so, <strong>Liz created Sseko Designs to employ those women to create unique and vibrant merchandise.</strong> But more importantly Sseko gives them a financial avenue to pursue a college degree that will provide a platform to create change.<br><em>Get tickets FOR FREE at the Union Info Desk to come hear her message</em>', 'teamup', '2155517', '2016-10-24T19:30:00', '2016-10-24T21:00:00', 2, 0),
(200, 'Adobe Research  Women-in-Technology Scholarship ', '', 'The Adobe Research Women-in-Technology Scholarship recognizes outstanding undergraduate female students anywhere in the world who are studying computer science or related degrees.<br>The Adobe Research Women-in-Technology Scholarship includes:<br><ul><br><li>A $10,000 award paid once.</li><br><li>A Creative Cloud subscription membership for one year.</li><br><li>An Adobe Research mentor.</li><br><li>An internship opportunity at Adobe for the 2017 summer.</li><br></ul><br><strong>Applications are due October 31, 2016</strong>, 5pm Pacific Time. A committee of Adobe researchers will review all applicants and select the winners at their discretion. Recipients are selected based on their academic record, a personal statement, and three letters of reference. Students may be invited for phone interviews following the initial review.', 'teamup', '2193528', '2016-10-24T00:00:00', '2016-10-24T23:59:00', 2, 0),
(198, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-10-22T18:00:00', '2016-10-22T20:00:00', 2, 0),
(199, 'Science Sundays: How Confidence Affects Decision Making and Action', 'Ohio Union U.S. Bank Conference Theatre', 'Although some people are more confident than others, nearly everyone wants to be more confident.  But why?  What good is confidence?   Petty explains where confidence comes from and the polarizing impact that it can have on our important judgments and behaviors.<br><em>Richard E. Petty, Distinguished University Professor of psychology at Ohio State, an expert on the impacts of social influence on judgment and behavior.</em><br>See <a href="https://artsandsciences.osu.edu/research/science-sundays" target="_blank" rel="noreferrer noopener external">Science Sundays</a> for more info.', 'teamup', '2155517', '2016-10-23T15:00:00', '2016-10-23T16:00:00', 2, 0),
(197, 'Ohio Avian Research Conference ', 'Granville, Ohio', '<em>For any student interested in learning about birds </em><br>This annual conference brings together professional ornithologists from museums and other academic institutions, high school, undergraduate, and graduate students, government agencies, as well as non-professional researchers and citizen scientists alike from all over Ohio to present and share their research projects with one another and with other interested individuals through oral and poster presentations (<a href="http://tuckercasey.wixsite.com/aacri-birds/oarc2016" target="_blank" rel="noreferrer noopener external">conference info</a>). <strong>This event will count as two events.</strong>', 'teamup', '2155517', '2016-10-22T00:00:00', '2016-10-22T23:59:00', 2, 0),
(196, 'OSU Night at COSI', 'COSI, 333 W Broad St', 'Free Admission to COSI with a valid BuckID. $5 COSI Bucks to the first 1000 guests. Continuous bus loop service from campus to COSI and back. beginning at 6:15 p.m. from the following CABS bus stops: Buckeye Village Community Center, Drake Performance Center, Haverfield House, Neil Building, Ohio Union. For more information contact Ryan Mouncey at <a href="mailto:mouncey.1@osu.edu" target="_blank" rel="noreferrer noopener external">mouncey.1@osu.edu</a>.', 'teamup', '2155517', '2016-10-21T18:30:00', '2016-10-21T22:30:00', 2, 0),
(194, 'HSPB''s Dips of the World', 'Kuhn Honors & Scholars House', 'Honors &amp; Scholars Programming Board (HSPB) welcomes you to come and enjoy Dips of the World! Come and taste some delicious dips from around the world! You will be able to try dips such as hummus, salsa, and chutney. This event offers a fun, educational experience for H&amp;S students to explore different cultures through food. We hope to see you there!', 'teamup', '979004', '2016-10-20T17:00:00', '2016-10-20T18:00:00', 2, 0),
(195, 'HSPB Trivia Night', '', 'Do you enjoy trivia? How about free pizza and prizes? If so, don''t miss the second Honors &amp; Scholars Programming Board''s Trivia Night on Thursday, October 20! Join for a great evening of fun, fast paced activity, and a great chance to show off your trivia knowledge with your friends! This month''s board will focus on topics in history, so come prepared! Students from any Honors or Scholars group are welcome, and you are not required to come with a team, but space is limited, so please RSVP at <a href="https://docs.google.com/forms/d/e/1FAIpQLSfyub0VFE-uqEv4ZrFdcUMQKfk9oaUhwWMTmfFAVZYhtgErUw/viewform" target="_blank" rel="noreferrer noopener external">https://docs.google.com/forms/d/e/1FAIpQLSfyub0VFE-uqEv4ZrFdcUMQKfk9oaUhwWMTmfFAVZYhtgErUw/viewform</a>. ', 'teamup', '979004', '2016-10-20T18:30:00', '2016-10-20T19:30:00', 2, 0),
(192, 'OUAB Flicks for Free ft. Suicide Squad', 'Ohio Union, U.S. Bank Conference Theater', 'First show: 6 PM<br>Second show: 8:30 PM<br>Free popcorn and beverages will be provided!<br> <br><em>It feels good to be bad...Assemble a team of the world''s most dangerous, incarcerated Super Villains, provide them with the most powerful arsenal at the government''s disposal, and send them off on a mission to defeat an enigmatic, insuperable entity. U.S. intelligence officer Amanda Waller has determined only a secretly convened group of disparate, despicable individuals with next to nothing to lose will do. However, once they realize they weren''t picked to succeed but chosen for their patent culpability when they inevitably fail, will the Suicide Squad resolve to die trying, or decide it''s every man for himself?</em>', 'teamup', '836635', '2016-10-19T18:00:00', '2016-10-19T22:00:00', 2, 0),
(193, 'Newman Technology Tour', 'Mainsfield, Ohio', '<em>For students in engineering fields</em><br>Please sign-up for the trip by end of the day on <strong>Friday, October 7th,</strong> and no ''backsies'', after you have signed up. *Note for first year-scholars: Students attending the trip, will be excused from Scholars Seminar on the week of October 17th. RSVP, by clicking <a href="https://goo.gl/forms/Mta6i1V9WI1USAfE3" target="_blank" rel="noreferrer noopener external">here</a>.<br><strong>Company''s Desctiption</strong>:  <a href="https://www.youtube.com/watch?v=XdG1Eivtdmw#action=share" target="_blank" rel="noreferrer noopener external">https://www.youtube.com/watch?v=XdG1Eivtdmw#action=share</a> ', 'teamup', '2155517', '2016-10-20T11:30:00', '2016-10-20T17:30:00', 2, 0),
(190, 'PSL Scholars Mock Presidential Debate', 'Moritz College of Law, Saxbe Auditorium', 'Join us the night of October 18 for the 2016 Mock Presidential Debate, featuring current PSL Scholar students portraying the VP and Presidential Candidates! Moderated by ABC6/Fox28 Political Reporter Ben Garbarek, the event will follow the Commission on Presidential Debates guidelines, but with an academic twist as we feature the nominees from the Democratic, Republican, *and* Libertarian parties! The VP Debate will begin at 7:00 p.m., followed by the Presidential Debate at approximately 7:40 p.m. Following the debates, join us in the Spin Room (the law school lounge) for refreshments and to meet the candidates!', 'teamup', '979004', '2016-10-18T19:00:00', '2016-10-18T20:30:00', 2, 0),
(191, 'Summer Research', 'Ramseyer 59', 'This event will focus on the <strong>summer interships</strong> available for students in the multple <strong>research</strong> fields. Addtionally, you will receive advice on how to be a successful applicant.<br> <br>If you are interested in attending, <strong>RSVP with Melissa Basford</strong>, Bio Sci Scholars Manager, at basford.18@osu.edu', 'teamup', '2155517', '2016-10-19T16:30:00', '2016-10-19T17:30:00', 2, 0),
(189, 'Dennis Learning Center', 'Macquigg Laboratory 264', '<em>Event is recommended for all students</em><br>Exams can be a stressful experience. You have to learn the material, take a test in a finite time and wait for your grade to post. But if you are strategic about how you prepare for your exams, you can be confident any exam you take will turn out just fine.  In this event,<strong> you will learn the optimal ways to prepare for your exams</strong> and the best strategies to take different types of tests. ', 'teamup', '836634', '2016-10-18T16:10:00', '2016-10-18T17:05:00', 2, 0),
(188, 'College of Arts and Sciences Education Abroad Fair', 'Great Hall Meeting Room, Ohio Union', 'Learn about Arts and Sciences Education Abroad opportunities in 2017, including:<br><ul><br><li>Global May Programs in 9 countries: Bolivia, Brazil, China, Great Britain, Hungary, Morocco, New Zealand, Spain and Uganda</li><br><li>Berlin, Then and Now: People, Places, and Experiences</li><br><li>Culture, Society and History of Zimbabwe</li><br><li>The Brazilian Experience</li><br><li>The British Invasion</li><br><li>Shanghai, 1750-2050</li><br><li>Global Hotspots of the Early Modern World: Buenos Aires, Argentina</li><br><li>Scientific Roots in Europe</li><br><li>History and Archaeology of Medieval Ireland</li><br><li>Economics of Immigration</li><br><li>HIV in Context: Tanzania</li><br><li>Mapping Our World – Southern Scandinavia</li><br><li>Environmental Sustainability in Costa Rica</li><br></ul><br>Meet faculty resident directors and past education abroad participants and learn about these and <strong>many other education abroad programs</strong>.', 'teamup', '836635', '2016-10-18T06:00:00', '2016-10-18T19:30:00', 2, 0),
(186, 'Sustainable Energy Phenomena from First Principles: From Fuel Cells to Fusion', '2004 Evans', '<em>This event is recommended for engineering students</em><br><strong>Emily A. Carter</strong> is the Dean of the School of Engineering and Applied Science and the Gerhard R. Andlinger Professor in Energy and the Environment, as well as a Professor of Mechanical and Aerospace Engineering and Applied and Computational Mathematics at Princeton University. Her current research is focused entirely on enabling discovery and design of materials for sustainable energy. ', 'teamup', '2155517', '2016-10-17T16:10:00', '2016-10-17T17:00:00', 2, 0),
(187, 'OUAB Presents: An Evening with Nyle DiMarco', 'Archie M. Griffin Ballroom, Ohio Union', 'null', 'teamup', '836635', '2016-10-17T19:30:00', '2016-10-17T21:30:00', 2, 0),
(182, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-10-15T18:00:00', '2016-10-15T20:00:00', 2, 0),
(183, 'Football @ Wisconsin', '', 'Make some time to watch this game', 'teamup', '836635', '2016-10-15T20:00:00', '2016-10-15T23:45:00', 2, 0),
(184, 'Women''s Soccer', 'Jesse Owens Memorial Stadium', 'null', 'teamup', '836635', '2016-10-16T14:00:00', '2016-10-16T16:00:00', 2, 0),
(185, '8 Dumb Things Well-Intentioned People Say that Widen the Diversity Gap', 'Multicultural Center Alonso Family Room', 'null', 'teamup', '836635', '2016-10-17T13:00:00', '2016-10-17T14:00:00', 2, 0),
(179, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-10-14T18:00:00', '2016-10-14T20:00:00', 2, 0),
(180, 'Men''s Soccer', 'Jesse Owens Memorial Stadium', 'null', 'teamup', '836635', '2016-10-15T14:00:00', '2016-10-15T16:00:00', 2, 0),
(181, 'Fallbreak BBQ / Picnic', 'TBD', 'If you are in the Columbus are and would like to be in a cook-out at the park this event is for you. I do not expect many students for this event but it will be a good time to relax and eat food.<br>RSVP, by clicking <a href="https://osu.az1.qualtrics.com/SE/?SID=SV_8k2XtupTfglDAr3" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-15T16:00:00', '2016-10-15T19:00:00', 2, 0),
(178, 'Graduate Engineering Open House', 'The Blackwell Inn and Conference Center', '<em>For students in Engineering</em><br> <br>The Graduate Engineering Open House functions as a<strong> graduate program preview f</strong>or prospective students at The Ohio State University’s Columbus campus. This is a two-day event  and provides an opportunity to learn about what College of Engineering has to offer you as a graduate student.<br> <br>To RSVP, click <a href="https://engineering.osu.edu/events/2016/10/graduate-engineering-open-house" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-14T08:00:00', '2016-10-15T15:00:00', 2, 0),
(177, 'Women''s Soccer', 'Jesse Owens Memorial Stadium', 'null', 'teamup', '836635', '2016-10-13T19:00:00', '2016-10-13T21:00:00', 2, 0),
(176, 'Climate Change, the Anthropocene and the Deep History of the Earth', 'Columbus Museum of Art, The Forum', '<em>Should be interesting for all students</em><br> <br>What is the evidence for <strong>human-driven climate change in recent history</strong>? What is coming to be called the “Anthropocene”? Brooke will provide a layman’s overview and briefly comment on the way forward for humanity. ', 'teamup', '2155517', '2016-10-13T19:00:00', '2016-10-13T21:00:00', 2, 0),
(173, 'Wingin'' It: How my science career took flight', 'Macquigg Laboratory 264', '<em>This event will be fantastic for pre-health students and students who are exploring different majors </em><br> <br>Jessica Caton, will be talking about her childhood goals of becoming a <strong>veterinarian</strong> and how that goal took her into different opportunities working with birds. She will also talk about transferable skills that she learned in college to work in outreach programs.', 'teamup', '836634', '2016-10-11T16:10:00', '2016-10-11T17:05:00', 2, 0),
(174, 'De-stress', 'Macquigg Laboratory 264', 'null', 'teamup', '836634', '2016-10-11T16:10:00', '2016-10-11T17:05:00', 2, 0),
(175, 'Autumn Break', '', 'No classes, offices open!', 'teamup', '836635', '2016-10-13T00:00:00', '2016-10-14T23:59:00', 2, 0),
(172, 'Women''s Self Defense Seminar', 'Women''s Field House', '<em>This event is designed for women in order to identify risk factors for women on a college campus.</em><br> <br>The Honors and Scholars Programing Board presents the Women''s Self Defense Seminar. The seminar is being given by Kim Valemore, a <strong>second degree black belt</strong> in Taekwondo. his event is open to all students who identify as women or non-binary, and is meant to be a safe space for you to feel comfortable discussing issues that impact women. Feel free to bring a partner because there will be a lot of partner work, but no partner is required to participate!<br>RSVP <a href="https://docs.google.com/forms/d/e/1FAIpQLScj6xHUA6_uRpgb_hAYAiTVftHSkPjlSnH8-VEv2z8Vj7ED3g/viewform?c=0&amp;w=1" target="_blank" rel="noreferrer noopener external">here</a>, for more details and location.', 'teamup', '979004', '2016-10-11T16:00:00', '2016-10-11T17:15:00', 2, 0),
(171, 'Caterpillar: Becoming the Employee of Choice', 'Journalism Building Rm 270', '<em>This event is hosted by the SWE (Society of Women Engineers), SHPE (Society of Hispanic Professional Engineers), and NSBE (National Society of Black Engineers) and is recommended for engineering, data analytics, and actuarial science majors. </em><br>Come listen to Tori Rollings, manager for Caterpillar’s Assurance of Supply Center (ASC) talk about how to be successful and be the employee of choice. Also in attendance will be Cheryl Verbeke, VP for Caterpillar Innovation<br>Tori Rollings is currently manager for Caterpillar’s Assurance of Supply Center (ASC). Her team uses analytics, big data, problem solving and business acumen to understand the Caterpillar Production Network and to identify, solve and prevent issues in the future.', 'teamup', '2155517', '2016-10-10T18:30:00', '2016-10-10T19:30:00', 2, 0),
(170, 'Current and Future U.S. Long-Baseline Neutrino Experiments: NOvA and DUNE', 'Physics Research Building, 4138', '<em>Seminar is for Physics students</em><br> <br><strong>Description of talk</strong>: Long-baseline neutrino experiments study beams of neutrinos near their source and at a far detector several hundred kilometers away. We study the changes in the beams between their generation and detection at the far detector.  Neutrinos come in three flavors: electron, muon, and tau. Our experiments produce a beam of muon neutrinos; as they travel, some of them “oscillate” into the other two kinds. By measuring the parameters that govern this oscillation, we gain a deeper understanding of the foundational laws that govern the material Universe.<br> <br>For more information, click <a href="https://physics.osu.edu/events/high-energy-physics-seminar-luke-corwin-south-dakota-school-mines-current-and-future-u.s." target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-10T15:00:00', '2016-10-10T16:00:00', 2, 0),
(168, 'Football vs Indiana', '', 'null', 'teamup', '836635', '2016-10-08T15:30:00', '2016-10-08T17:00:00', 2, 0),
(169, 'Exploring Majors Fair: Engineering and Beyond', 'Physics Research Building Atrium', '<em>This will be a great event for all students</em><br> <br>Want to find a class to take next semester to explore a major? If so, join the 2016 Exploring Majors Fair! Stop by and <strong>chat with advisors</strong> and students from a variety of STEM related academic areas in one convenient location, right before scheduling classes for next semester starts!<br> <br>Aeronautical and Astronautical Engineering<br />Atmospheric Sciences, Geographic Information Science, Air Transportation Geography<br />Aviation<br />Biomedical Engineering<br />Business (Fisher College of)<br />Chemical and Biomolecular Engineering<br />Chemistry<br />Civil and Environmental Engineering<br />Computer Science and Engineering<br />Data Analytics<br />Earth Sciences<br />Education and Human Ecology (Exercise Science, Human Nutrition, STEM Education)<br />Electrical and Computer Engineering<br />Entomology<br />Environment and Natural Resources (Environment, Economy, Development and Sustainability; Environmental Sciences; Environmental Policy and Decision Making)<br />Food, Agricultural, Biological and Ecological Engineering<br />Food, Agriculture, and Environmental Sciences<br />Industrial and Systems Engineering<br />Knowlton School of Architecture<br />Languages, Literatures and Cultures<br />Materials Science and Engineering<br />Mathematics and Actuarial Sciences<br />Mechanical Engineering<br />Physics and Engineering Physics<br />Pre-Health<br />Pre-Law<br />Undergraduate Research', 'teamup', '2155517', '2016-10-10T11:00:00', '2016-10-10T14:00:00', 2, 0),
(167, 'Corn Maze', '', '<em>Event is recommended for any scholar. </em><br> <br>We will be participating in some Fall fun with three other Scholars programs. The event will be on a Friday and the cost is <strong>$5,</strong> which includes your <strong>transportation, access to the maze, a hay ride, a small pumpkin, and other activities</strong>.<br> <br>Please <a href="https://goo.gl/forms/npT43mSWKp814c9r2" target="_blank" rel="noreferrer noopener external">RSVP</a> and pay no later than 9/26 (space is limited, so first come, first serve!)', 'teamup', '2155517', '2016-10-07T16:30:00', '2016-10-07T20:30:00', 2, 0),
(166, 'Proton-Coupled Electron Transfer Chemistry of Energy Conversion Catalysis', 'CBEC 130', '<em>This event might be of high interest for students in science and engineering.</em><br> <br>Hughes to speak for October Emeritus Professor Nocera s the <strong>Patterson Rockwood Professor of Energy at Harvard</strong> and he is widely recognized as one of the <strong>world’s leading researchers in renewable energy</strong>. His group has pioneered studies of the basic mechanisms of energy conversion in biology and chemistry. He accomplished a solar fuels process of photosynthesis–the splitting of water to hydrogen and oxygen using sunlight and translated this science to produce the artificial leaf, which was named by Time magazine as Innovation of the Year for 2011. <br> <br>For more information, click <a href="http://chemistry.osu.edu/seminars/evans/2016" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-07T16:10:00', '2016-10-07T17:30:00', 2, 0),
(165, 'Financial Friday: Credit - Myths vs Facts', 'Milestones Room, Ohio Union', '<em>For all students seeking personal finance management</em><br> <br>Join the Student Life Student Wellness Center’s Scarlet and Gray <strong>Financial Wellness program</strong> to learn all about credit and how you can ensure you are sifting through the myths and the facts.', 'teamup', '836635', '2016-10-07T16:00:00', '2016-10-07T17:30:00', 2, 0),
(164, 'Society of Women Engineers Cardinal Health Tour', 'Cardinal Health', 'Society of Women Engineers (SWE) is hosting a Cardinal Health Tour. This event is highly recommended for women in engineering of any year.  <a href="https://docs.google.com/forms/d/e/1FAIpQLSc51rMjOg0fFAT9UQBKSU19SM2o-Vu43_34izy3uBJoYvVYeA/viewform?c=0&amp;w=1" target="_blank" rel="noreferrer noopener external">RSVP was required for this event.</a>', 'teamup', '2155517', '2016-10-07T13:30:00', '2016-10-07T16:00:00', 2, 0),
(163, 'OUAB Karaoke Night', 'Woody''s Tavern', 'null', 'teamup', '836635', '2016-10-06T19:00:00', '2016-10-06T21:30:00', 2, 0),
(162, 'A Complete Artificial Photosynthesis', 'McPherson 1000', '<em>This event might be of high interest for students in science and engineering.</em><br> <br>Hughes to speak for October Emeritus Professor Nocera s the <strong>Patterson Rockwood Professor of Energy at Harvard</strong> and he is widely recognized as one of the <strong>world’s leading researchers in renewable energy</strong>. His group has pioneered studies of the basic mechanisms of energy conversion in biology and chemistry. He accomplished a solar fuels process of photosynthesis–the splitting of water to hydrogen and oxygen using sunlight and translated this science to produce the artificial leaf, which was named by Time magazine as Innovation of the Year for 2011. <br> <br>For more information, click <a href="http://chemistry.osu.edu/seminars/evans/2016" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-06T16:00:00', '2016-10-06T17:15:00', 2, 0),
(161, 'Pre-Health Collegium Speaker', 'Hagerty Hall 071', '<em>This event will be useful for students interested in medical school</em><br> <br>Elana is a Collegium Alumni, graduating from Ohio State in 2016, and is <strong>currently an MD student at the Ohio State School of Medicine</strong>. Elana will be discussing her experience as a Pre-Med student at Ohio State, the medical school admissions process, and her time so far as a medical student and will be available for Q&amp;A<br> <br>To attend this event, RSVP <a href="https://docs.google.com/forms/d/e/1FAIpQLScNXBkX5Pkm-IAujlWtR6tPa7fV0qCL7Cmmov53KuP8cSNd5Q/viewform" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '979004', '2016-10-05T18:30:00', '2016-10-05T19:30:00', 2, 0),
(160, 'Science Cafe: The Microbiome in Health and Disease: Bugs, Guts, and Drugs', '18th Avenue Library (Research Commons in 3rd Floor) ', '<em>Students in pre-medical fields, biology, and similar fields are encouraged to attend.</em><br>Topic: <strong>The Microbiome in Health and Disease: Bugs, Guts, and Drugs</strong><br>Dr. Nicole Kwiek is a Clinical Assistant Professor of Pharmacology and the Director of Undergraduate Studies at the Ohio State University College of Pharmacy. She is also the Director of the Generation Rx Laboratory at the Center of Science and Industry (COSI) and co-leads the Generation Rx Initiative, a learning community of OSU faculty, staff, and students studying the problem of prescription drug misuse.<br>Visit the <a href="https://library.osu.edu/news/science-cafe/" target="_blank" rel="noreferrer noopener external">Science Cafe website</a> for more info!', 'teamup', '2155517', '2016-10-05T18:30:00', '2016-10-05T19:30:00', 2, 0),
(159, 'OUAB Flicks for Free ft. Nerve', 'U.S. Bank Conference Theater, Ohio Union', 'First show: 6 PM<br>Second show: 8:30 PM<br>Location: U.S. Bank Conference Theater (Ohio Union)<br>Free popcorn and beverages will be provided!<br> <br><em>Lou Clark knows lots of things. She knows how many footsteps there are between the bus stop and home. She knows she likes working in The Buttered Bun tea shop and she knows she might not love her boyfriend Patrick. What Lou doesn''t know is she''s about to lose her job or that knowing what''s coming is what keeps her sane. Will Traynor knows his motorcycle accident took away his desire to live. He knows everything feels very small and rather joyless now and he knows exactly how he''s going to put a stop to that. What Will doesn''t know is that Lou is about to burst into his world in a riot of color. And neither of them knows they''re going to change each other for all time</em>', 'teamup', '836635', '2016-10-05T18:00:00', '2016-10-05T22:00:00', 2, 0),
(158, '2nd Year Scholars Monthly Meeting', 'Mendenhall Lab 115', 'Capstone Project Hours Log<br><a href="https://osu.az1.qualtrics.com/jfe/form/SV_882L66zhKtdQACx" target="_blank" rel="noreferrer noopener external">https://osu.az1.qualtrics.com/jfe/form/SV_882L66zhKtdQACx</a>', 'teamup', '2155500', '2016-10-05T16:00:00', '2016-10-05T17:30:00', 2, 0),
(157, 'Budgeting and Financial Goal Setting', 'Barbie Tootle Room, Ohio Union', '<em>For all students seeking better grasp of personal finances</em><br> <br>One of the most important aspects of<strong> financial wellness</strong> is an understanding of the basics.  This workshop will help you to start on your path to greater financial capability and understanding!  Topics include: budgeting, banking and credit.', 'teamup', '836635', '2016-10-05T12:00:00', '2016-10-05T13:00:00', 2, 0),
(156, 'Healthcare-Associated Infections: A Personal and Public Healthcare Tragedy', 'Faculty Club, Grand Lounge', '<em>This event is suited for students with an interest in health-related careers</em><br> <br>Hughes to speak for October Emeritus Academy. His presentation will centered on <strong>healthcare-associated infections</strong>. To assist to this event, you must RSVP.<br> <br>To RSVP, click <a href="https://docs.google.com/forms/d/e/1FAIpQLScKolY2-jIKlPttAFXe0fBr-XB5oOHguGOE5lHi3cAFhIzcZg/viewform?c=0&amp;w=1" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '2155517', '2016-10-05T04:00:00', '2016-10-05T05:30:00', 2, 0),
(153, 'Actuarial Science and Risk Management ', 'Cockins Hall 240', '<em>For students in actuarial science</em><br> <br>Representatives of diffrent companies will have <strong>presentations on different areas of actuarial and risk management practices</strong>, will talk about the business, organization, and culture of their companies, and will explain what they are expecting from a candidate.', 'teamup', '2155517', '2016-10-03T18:30:00', '2016-10-03T20:00:00', 2, 0),
(154, 'Scavenger Hunt', 'Campus', 'Scholars, feel free to use this time to work on completing the scavenger hunt. The scavenger hunt counts as an STEM EE Scholars event that you can log. ', 'teamup', '836634', '2016-10-04T16:10:00', '2016-10-04T17:05:00', 2, 0),
(155, 'Anatomy Graduate Program Eat and Explore', 'Jennings 140', '<em>This program is geared for students interested in Anatomy Graduate Programs</em><br> <br><strong>RSVP with Melissa Basford</strong>, Bio Sci Scholars, at  basford.18@osu.edu', 'teamup', '2155517', '2016-10-04T17:30:00', '2016-10-04T18:30:00', 2, 0),
(152, 'Wellness Ambassador', '', '<em>For students interested in  health sciences or looking for a long-term event.</em><br> <br>Wellness Ambassadors serve as a liaison between Student Life and other students on campus. Wellness Ambassadors play a vital role in supporting the mission of Student Life, which aims to<strong> promote wellness among Ohio State students and their communities</strong>. Wellness Ambassadors deliver educational presentations in a variety of settings and work as a team to develop and implement events highlighting the 9 dimensions of wellness. <br> <br>Applications due, on Sunday, October 30.  For more information, click <a href="https://swc.osu.edu/wellness-initiatives/wellness-ambassadors/" target="_blank" rel="noreferrer noopener external">here</a>.', 'teamup', '836635', '2016-10-03T00:00:00', '2016-10-03T23:59:00', 2, 0),
(151, 'SMART Scholarship', '', '<em>This is a STEM Scholarship for all undergrad students, specifically those interested in Department of Defense labs. Note the conditions of appointment require you to be willing to accept post-graduate emplloyement with the DoD.</em><br>The Science, Mathematics And Research for Transformation (SMART) Scholarship for Service Program is an opportunity for students pursuing an undergraduate or graduate degree in Science, Technology, Engineering, and Mathematics (STEM) disciplines to receive a full scholarship and be gainfully employed upon degree completion. Students pursuing degrees related to the following are encouraged to apply:<br><em>*Students who are currently Freshman or enrolled in a First Year Associate’s Program applicants must report an ACT or SAT Reasoning Test Score. Subject tests are not required. In addition, individuals who apply during their Freshman/First Year must obtain a minimum cumulative 3.0 GPA on a 4.0 scale during the fall academic term of their Freshman/First Year. Freshman/First Year Associate''s Program applicants will be required to submit an official transcript reflecting their fall academic term grades to establish compliance with this requirement.</em><br><a href="http://smart.asee.org/apply_/application_instructions" target="_blank" rel="noreferrer noopener external">http://smart.asee.org/apply_/application_instructions</a> ', 'teamup', '2193528', '2016-10-03T00:00:00', '2016-10-03T23:59:00', 2, 0),
(149, 'Men''s Ice Hockey vs. Wilfrid Laurier', '', 'null', 'teamup', '836635', '2016-10-02T16:00:00', '2016-10-02T18:30:00', 2, 0),
(150, 'Autumn Enrichment Grant Applications ', '', '<em>Due November 25, 2016</em><br> <br>Apply for an Honors &amp; Scholars Enrichment Grant! The scholarship amount will range based on the student''s proposal, with <strong>a maximum award of $3,000</strong>, and will be awarded through a competitive application process. Funds can be utilized for a variety of purposes, including, but not limited to research, creative work and study abroad. <br> <br>For more information visit H&amp;S <a href="http://honors-scholars.osu.edu/current-students/opportunities" target="_blank" rel="noreferrer noopener external">website</a> or contact Lindsey Chamberlain at  chamberlain.55@osu.edu.', 'teamup', '2193528', '2016-10-03T00:00:00', '2016-10-03T23:59:00', 2, 0),
(148, 'Running Water 5k & 10k', 'OSU RPAC', 'The event is a <strong>5K/10K</strong> race that people can do individually or in teams of four.  People can also walk or run carrying the pack filled with water to understand what it is like to have to carry water for several miles.  A really good article from NPR highlights this in case you are interested:  <a href="http://www.npr.org/sections/goatsandsoda/2016/07/07/484793736/millions-of-women-take-a-long-walk-with-a-40-pound-water-can" target="_blank" rel="noreferrer noopener external">http://www.npr.org/sections/goatsandsoda/2016/07/07/484793736/millions-of-women-take-a-long-walk-with-a-40-pound-water-can</a>.<br> <br>To actually register for the race, folks can go to <strong>Premier Races</strong> at <a href="https://premierraces.com/" target="_blank" rel="noreferrer noopener external">https://premierraces.com/</a>.  Any assistance with getting the word out via social media or word of mouth would be greatly, greatly appreciated.  We are aiming to have 50-100 people for this considering it is our first year.', 'teamup', '836635', '2016-10-02T08:00:00', '2016-10-02T11:00:00', 2, 0),
(285, 'HSPB Service Snowman', 'Torres, Park-Stradley, Smith-Steeb, Taylor Tower, and Kuhn House', 'Want to give a kid a reason to smile? Want to make a child’s holiday season? HSPB is throwing a two-week long event from November 21st-December 2nd 12am-4pm called Service Snowman. In Torres, Park-Stradley, Smith-Steeb, Taylor Tower, and the Kuhn House there will be a snowman hanging up in the lobby. All you have to do is grab a tag, go out and buy the gift on the tag and return it to any of the designated locations above. It is a perfect thing to do over thanksgiving day break! Go out and make a little kids holiday season!', 'teamup', '979004', '2016-11-21T00:00:00', '2016-12-02T16:00:00', 2, 0),
(286, 'Thanksgiving Break - No Classes', '', 'No classes, offices closed.', 'teamup', '836635', '2016-11-23T00:00:00', '2016-11-25T23:59:00', 2, 0),
(287, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-11-25T19:00:00', '2016-11-25T21:00:00', 2, 0),
(288, 'Football vs Michigan', '', 'null', 'teamup', '836635', '2016-11-26T00:00:00', '2016-11-26T15:00:00', 2, 0),
(289, 'Women''s Volleyball', 'St. John Arena', 'null', 'teamup', '836635', '2016-11-26T19:00:00', '2016-11-26T21:00:00', 2, 0),
(290, 'Society of Women Engineers Scholarships (Sophomores and Up)', '', 'The SWE Scholarship Program provides financial assistance to women studying baccalaureate or graduate programs, in preparation for careers in engineering, engineering technology and computer science. In 2015, SWE awarded approximately 220 new and renewed scholarships valued at over $660,000. <br><a href="http://societyofwomenengineers.swe.org/scholarships" target="_blank" rel="noreferrer noopener external">See here for more details</a>. Sophomores and up can apply from December to January/February. ', 'teamup', '2193528', '2016-11-28T00:00:00', '2016-11-28T23:59:00', 2, 0),
(291, 'Final Review', 'Macquigg Laboratory 264', 'Upperclassmen STEM Scholars will be there to help out with any questions that you have!<br>There will be Insomnia cookies!', 'teamup', '836634', '2016-11-29T16:10:00', '2016-11-29T17:05:00', 2, 0),
(292, 'Business Builders Club: Idea Pitch', 'Mason Hall', '<em>This event is for anyone interested in entrepreneurship! </em><br>IdeaPitch is the Business Builders Club’s flagship event. IdeaPitch is a night of professional skill building, networking opportunity, food, fun and entrepreneurial spirit that brings together students, professors, faculty, BBC Alumni, and working professionals. Each semester the BBC gives its members the opportunity to present their idea to a panel of judges and fellow members for a chance to win seed funding for their business. IdeaPitch is not just a student business plan competition; it is one of the most rewarding experiences The Ohio State University has to offer and it continues to get bigger and better each semester. ', 'teamup', '2155517', '2016-11-29T19:30:00', '2016-11-29T21:30:00', 2, 0),
(293, 'OUAB: Steaming with Edward Snowden', 'Performance Hall, Ohio Union', 'Attend a <strong>live stream</strong>, from Russia, with <strong>Edward Snowden.</strong> STEM EE Scholars will meet outside the <em>Union Performance Hall</em> at <strong>7:00 PM</strong>. STEM EE Scholars will have the opportunity to ask questions to Edward Snowden!<br><em>Chloe ten Brink</em>, First-Year STEM EE Scholar, is involved with OUAB, and has allocated <strong>70 tickets for STEM EE Scholars</strong>. If you want to secure your ticket, please <a href="https://docs.google.com/forms/d/e/1FAIpQLScPmK4JGNSTVmA2WDEwO1rLziTHnWf1pvE_H0Qe5xIkrvmahA/viewform" target="_blank" rel="noreferrer noopener external">RSVP</a> no later than 5:00PM. You can learn more about this event in this <a href="http://thelantern.com/2016/10/edward-snowden-set-to-come-to-ohio-state-via-satellite/" target="_blank" rel="noreferrer noopener external">article</a>.', 'teamup', '2155517', '2016-11-30T19:00:00', '2016-11-30T21:00:00', 2, 0);

-- --------------------------------------------------------

--
-- Table structure for table `event_tags`
--

CREATE TABLE `event_tags` (
  `event_tag_id` int(11) NOT NULL AUTO_INCREMENT,
  `event_id` int(11) NOT NULL,
  `tag` int(11) NOT NULL,
  PRIMARY KEY (`event_tag_id`),
  UNIQUE KEY `event_tag_id_UNIQUE` (`event_tag_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


--
-- Dumping data for table `event_tags`
--

INSERT INTO `event_tags` (`event_tag_id`, `event_id`, `tag`) VALUES
(0, 266, 7);

-- --------------------------------------------------------

--
-- Table structure for table `sessions`
--

CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` int(11) NOT NULL,
  `user_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`session_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `tags`
--

CREATE TABLE IF NOT EXISTS `tags` (
  `tag_id` int(11) NOT NULL,
  `name` tinytext NOT NULL,
  `leaf` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`tag_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tags`
--

INSERT INTO `tags` (`tag_id`, `name`, `leaf`) VALUES
(1, 'Academic', NULL),
(2, 'STEM', NULL),
(3, 'Engineering', NULL),
(4, 'Computer Science', 1),
(5, 'Mechanical', NULL),
(6, 'Math', 1),
(7, 'Medical', 1),
(8, 'Science', 1),
(9, 'Art', 1),
(10, 'Business', 1),
(11, 'Athletics', NULL),
(12, 'Sporting Events', 1),
(13, 'Social', NULL),
(14, 'Movies', 1),
(15, 'Music', 1),
(16, 'Other', 1),
(42, 'Scholarships', NULL),
(100, 'Undergraduate Student', 1),
(101, 'Graduate Student', 1),
(102, 'Staff / Faculty', 1),
(103, 'Other', 1);

-- --------------------------------------------------------

--
-- Table structure for table `tags_relations`
--

CREATE TABLE IF NOT EXISTS `tags_relations` (
  `relation_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent` int(11) DEFAULT NULL,
  `child` int(11) DEFAULT NULL,
  `weight` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`relation_id`),
  UNIQUE KEY `relation_id_UNIQUE` (`relation_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=20 ;

--
-- Dumping data for table `tags_relations`
--

INSERT INTO `tags_relations` (`relation_id`, `parent`, `child`, `weight`) VALUES
(1, 1, 4, 25),
(2, 2, 4, 50),
(3, 3, 4, 75),
(4, 1, 6, 50),
(5, 2, 6, 50),
(6, 1, 5, 25),
(7, 2, 5, 50),
(8, 3, 5, 75),
(9, 1, 7, 50),
(10, 2, 7, 75),
(11, 1, 8, 50),
(12, 2, 8, 75),
(13, 1, 9, 50),
(14, 1, 10, 50),
(15, 1, 10, 50),
(16, 11, 12, 50),
(17, 13, 14, 75),
(18, 13, 15, 75),
(19, 13, 16, 75);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL,
  `email` tinytext,
  `password` text,
  `access` int(11) DEFAULT '0',
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `email`, `password`, `access`) VALUES
(1, 'email', 'password', 0);

-- --------------------------------------------------------

--
-- Table structure for table `users_preferences`
--

CREATE TABLE IF NOT EXISTS `users_preferences` (
  `preference_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `tag_id` int(11) DEFAULT NULL,
  `weight` tinyint(4) DEFAULT '1',
  PRIMARY KEY (`preference_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users_preferences`
--

INSERT INTO `users_preferences` (`preference_id`, `user_id`, `tag_id`, `weight`) VALUES
(1, 1, 14, 2),
(2, 1, 4, 2),
(3, 1, 4, 2);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

ALTER table events ADD FULLTEXT event_search(`name`, `location`, `desc`);